spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaohuixingjia/studySpringCloud/SpringCloudConfigTest/src/main/
          search-paths : resources
      label: master
server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false