spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaohuixingjia/studySpringCloud/SpringCloudConfigTest/
          search-paths:
            - src/main/resources/
      label: master
server:
  port: 8761

