spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaohuixingjia/studySpringCloud
          search-paths : CommonConfig
      label: master
server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false